[package]
name = "denon-avr-remote"
version = "1.0.0"
edition = "2021"
description = "Denon and Marantz AVR IP control library"
license = "All Rights Reserved"
autobins = false

[lib]
name = "denon_avr_remote"
path = "src/lib.rs"

[[bin]]
name = "denon-avr-remote"
path = "src/bin/denon-avr-remote/main.rs"

[dependencies]
if-addrs = "0.15"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
