[package]
name = "denon-avr-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
[[bin]]
name = "denon-avr-remote"
path = "src/main.rs"
[dependencies]
denon-avr-application = { path = "../../crates/application" }
denon-avr-domain = { path = "../../crates/domain" }
denon-avr-infrastructure = { path = "../../crates/infrastructure" }
